db:
  mongodb:
    url: 'cluster0.llcca.mongodb.net'
    database: 'coinlist'
    user: 'coinlister'
    password: 'p7nZUdHzkfYAJ2Z'
    params:
      retryWrites: true
      w: 'majority'
storage:
  bucket:
    # TODO: Should be changed to coinlister-bucket
    name: 'coinlister_proxies_bucket'

